name: C++ Build and Test

on:
  push:
    branches:
      - main  # Adjust this branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./tests/test_executable